version: "3.8"

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    volumes:
      #- ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./app/database/capturepg_final.sql:/docker-entrypoint-initdb.d/capturepg_final.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=capture
  api:
    build: .
    # command: uvicorn app.server:app --host 0.0.0.0 --port 80
    # command: bash -c "uvicorn app.server:app --host 0.0.0.0 --port 80 --reload"
    command: bash -c "./start.sh"
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
